spring:
  profiles:
    active: dev
    include:
      - fake-data
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:iasb;DB_CLOSE_DELAY=-1;IGNORECASE=true;
    username: sa
    password:
  h2:
    console:
      enabled: true
application:
  custom-property: Custom property DEV
